### ISSUE TITLE
Assign To Post Types

### ISSUE THREAD

**Issue by skynet** [wpmetabox/mb-custom-taxonomy#2]
Not able to Assign To Post Types: Post

Why?

**Comment by alex-solovyev** [comment]
Hi @rilwis,

We are having a similar issue using this plugin together with wp_glossary plugin:
the glossary registers its custom type using the following code:

add_action( 'init', array( __CLASS__, 'register_post_types' ) );

The custom type of wp_glossary plugin is not listed in the list "Assign To Post Types" util I change the priority to 9:

add_action( 'init', array( __CLASS__, 'register_post_types' ), 9 );

Regards,
Alexey

**Comment by alex-solovyev** [comment]
btw, the example in WP docs at https://codex.wordpress.org/Function_Reference/register_post_type
uses the same action "init" and the default priority to register a custom post type, so the code should work, but unfortunately it does not without tweaking the priority.

**Comment by rilwis** [comment]
Hi @alex-solovyev and @skynet,

The problem is the priority of hook that Meta Box plugin uses. I've fixed it in the Meta Box plugin (on Github).
